package life.majiang.community;

import org.junit.jupiter.api.Test;
import org.junit.platform.commons.annotation.Testable;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

import life.majiang.community.mapper.CommentMapper;
import life.majiang.community.mapper.QuestionMapper;
import life.majiang.community.model.Comment;
import life.majiang.community.model.CommentExample;
import life.majiang.community.model.Question;

import javax.sql.DataSource;
import java.sql.SQLException;


@SpringBootTest
public class CommunityApplicationTests {
	
	@Autowired
	private CommentMapper commentMapper;
	@Autowired
	private QuestionMapper questionMapper;
	
	@Test
	public void test() {
		CommentExample commentExample = new CommentExample();
		commentExample.createCriteria()
				.andParentIdEqualTo(16)
				.andTypeEqualTo(1);
		
		System.out.println(commentMapper.selectByExample(commentExample));
	}

	
	/*
	 *   <select id="selectByExampleWithBLOBsWithRowbounds" parameterType="life.majiang.community.model.QuestionExample" resultMap="ResultMapWithBLOBs">
    <!--
      WARNING - @mbg.generated
      This element is automatically generated by MyBatis Generator, do not modify.
      This element was generated on Tue Mar 28 10:34:13 JST 2023.
    -->
    select
    <if test="distinct">
      distinct
    </if>
    <include refid="Base_Column_List" />
    ,
    <include refid="Blob_Column_List" />
    from question
    <if test="_parameter != null">
      <include refid="Example_Where_Clause" />
    </if>
    <if test="gmtCreate != null">
      order by ${gmt_create} DESC
    </if>
  </select>
	 */
	/*
	 * @Test public void test1() {
	 * questionMapper.selectByExampleWithBLOBsWithRowbounds(null, null) }
	 */
}
